# Generated by Django 3.1.5 on 2021-01-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tweet',
        ),
    ]
