# Generated by Django 3.1.5 on 2021-01-26 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_remove_profile_tweet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retweet',
            old_name='Profile',
            new_name='profile',
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='Media/Profile/'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='media',
            field=models.FileField(upload_to='Media/'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.profile'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.profile')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.tweet')),
            ],
        ),
    ]
